### ISSUE TITLE
enketo-preview-in-modal fixes

### ISSUE THREAD

**Issue by MartijnR** [SEL-Columbia/formhub#1089]
this would fix scrolling issues, I believe:

``` css
#preview-modal{
   overflow: hidden;
}
#preview-modal modal-body{
   overflow: hidden;
}
#preview-modal iframe{
  overflow-x: hidden;
  overflow-y: auto;
}
```

other issue to be fixed on enketo-side: https://github.com/modilabs/enketo/issues/443
